### ISSUE TITLE
[Elao - App - Docker] Add certificate in the container

### ISSUE THREAD

**Issue by maximecolin** [manala/manala-recipes#196]
If you try to access the app through http within the container with your-app.ela.ooo it works, but only with http. With https the certificate is invalid (or unknown/untrusted ?).

Fixed by executing this inside the container :

```
sudo cp ./.manala/certificates/ca.crt /usr/local/share/ca-certificates/
sudo update-ca-certificates
```

**Comment by nervo** [comment]
Fixed by https://github.com/manala/manala-recipes/commit/00a6a169cd27902622c569e0a023ba4a1f667dcb

Thx @maximecolin ❤️
