### ISSUE TITLE
[Elao - App] Automatic security/audit make targets

### ISSUE THREAD

**Issue by nervo** [manala/manala-recipes#52]
💡 Let `make security.foo` (or `make audit.foo`) automatically generated, based on presence of:

* `composer.lock` for symfony
* `yarn.lock` for yarn
* `package-lock.json` for npm

No more such targets in project makefiles :)

**Comment by benji07** [comment]
@nervo when you do a `manala up` you only look for information inside of the .manala.yml file ? 

If so, the manala.yaml file should be aware of your lock files (by adding configuration) ?

**Comment by nervo** [comment]
@benji07 such lock files detection happens on-the-fly in the Makefile :)

**Comment by benji07** [comment]
@nervo what about repositories with multiple app inside of them ?

This work, but what if your package-lock.json is not il your root directory

```
ifneq ($(wildcard package-lock.json),)
audit.test:
	npm audit ; RC=$${?} ; [ $${RC} -gt 2 ] && exit $${RC} || exit 0
endif
```

**Comment by nervo** [comment]
@benji07 it should be all right, as every makefile app - even in sub-project - include `.manala/Makefile` where magic happens :)
To be tested....

**Comment by nervo** [comment]
Please note also that if the target is totally include in the `ifneq/endif`, that will disable the auto-completion..
How about something like:
```
audit.test:
ifneq ($(wildcard package-lock.json),)
	npm audit ; RC=$${?} ; [ $${RC} -gt 2 ] && exit $${RC} || exit 0
else
	$(message_warning, No npm package found little canaillou)
endif
```

**Comment by nervo** [comment]
And the generated help should also be taken in consideration !
