### ISSUE TITLE
[Elao - App] mysqldump in CI

### ISSUE THREAD

**Issue by maximecolin** [manala/manala-recipes#53]
I tried to use a mysql fixtures cache that dump the database and reload it between each tests in order to speed up fixtures loading. This cache use `mysqldump` to dump the database, which is available in the VM but not in the CI.

**Comment by ogizanagi** [comment]
Isn't adding `mysql-client` to `system.apt.packages` enough? https://manala.github.io/manala-recipes/recipes/elao.app/#system

**Comment by nervo** [comment]
`mysql-client` package is now embedded in both development and integration environments :)
