### ISSUE TITLE
[Lazy - None]

### ISSUE THREAD

**Issue by Tom32i** [manala/manala-recipes#71]
Y'aurais moyen d'avoir un Lazy.None : qui contient juste un debian par defaut ? Pas de nginx, rien.

Cas d'usage : ça me permet de simuler une fresh install de debian sur laquelle j'éxécute mon provisionning ansible custom pour mon serveur dédié.

**Comment by nervo** [comment]
Ah ah, j'aime bien l'idée :)
mais autant faire un `docker run -ti debian` nan ?
