### ISSUE TITLE
[Elao - App] Allow release to other environnements 

### ISSUE THREAD

**Issue by Tom32i** [manala/manala-recipes#74]
Actuellement on ne peut configurer de release que pour deux environnement "staging" et "production".

Je voudrais configurer une release vers un 3ème environnement "beta" (par exemple), j'aurais donc : 
- make release@staging deploy@staging
- make release@beta deploy@beta
- make release@production deploy@production

Mais il ne me laisse pas faire car les seuls options acceptées sont "staging" et "production", ça semble être en dur.
Techniquement ce serait possible ou c'est chiant ?

Merci :)

**Comment by nervo** [comment]
C'est pas grand chose à faire, c'est au niveau de la validation jsonschema ici: https://github.com/manala/manala-recipes/blob/master/elao.app/.manala.yaml#L169
C'est volontairement bridé pour un peu d'uniformité dans les projets elao.
Deux solution donc ici:
- on rajoute "beta" dans la liste des possibles
- on dégage le bridage fort, et on s'assure juste que ce soit une string (peut-être une regex pour pas avoir d'emojis :) )

Une/Des opinion ?

**Comment by ogizanagi** [comment]
Juste une string 👍 
Je ne vois pas de bonne raison pour le bridage. On est déjà bien habitué à Elao à utiliser `staging` et `production` de base. Pas besoin de pédagogie par la restriction dans l'outil 😄 

Cas spécial rencontré: j'ai déjà eu à faire une release spéciale pour un projet client, qui n'était qu'une version temporaire envoyée en production, mais qui n'appartiendrait jamais au code source de `master`.

**Comment by maximecolin** [comment]
Je vote aussi pour une simple string, je pensais que c'était déjà comme ça à vrai dire 😅 On est pas à l'abri d'un projet avec preprod par exemple, ou de travailler avec un client qui utilise d'autre terme que production et staging.

**Comment by nervo** [comment]
Ah ah, bon ben c'était une idée de merde ce bridage :)
ca vous irait cette regex ? `^[a-z]+$` (que des lettres en minuscules, et au moins une)

**Comment by ogizanagi** [comment]
Yes, fine 👌

**Comment by Tom32i** [comment]
👍
