### ISSUE TITLE
[Elao - App] Vagrant box update

### ISSUE THREAD

**Issue by maximecolin** [manala/manala-recipes#76]
Maintenant que le Vagrantfile est dans .manala, `vagrant box update` n'est plus possible à la racine du projet et il ne me 
semble pas avoir de proxy dans le makefile manala. La seule solution que j'ai trouvé c'est d'exécuter `vagrant box update` depuis le répertoire `.manala`.

**Comment by nervo** [comment]
Yep, voila un point interessant.
En préambule, je précise que le vagrant box update est nettement moins sensible aujourd'hui, dans la mesure ou nous utilisons une image publique TRES générique. Autrement dit, l'update ne sert qu'a avoir des versions plus récentes des packages pré-installés.
Cela étant, il y a du coup plusieurs solutions:
1) méthode proxy (`vagrant.update` ? un peu bizarre dans la mesure ou aucune autre methode n'est préfixée par `vagrant`. A voir)
2) une bafouille dans le README.md qui explique d'aller dans le `.manala`
3) une autre bafouille mais concernant cette fois l'update global des images
4) une autre solution à laquelle je n'aurais pas pensé ?

Concernant le point 3, ca ressemble à des trucs comme ca:
```
  vagrant box outdated --global
  vagrant box update --box bento/debian-9
```

**Comment by ogizanagi** [comment]
La bafouille 2 ou 3 me semble suffisante 👍
