### ISSUE TITLE
[Elao - App] Auto certificates for SSL and HTTPS support

### ISSUE THREAD

**Issue by Tom32i** [manala/manala-recipes#78]
> 1. générer un CA dans un repertoire .manala/certificate s(c’est celui la qu’on va mettre dans les navigateurs) un petit fichier NOTES.md ou je ne sais quoi pour expliquer comment on a fait et surtout que c’est QUE pour du dev
> 2. utiliser le module ansible [openssl-certificate-module](https://docs.ansible.com/ansible/2.9/modules/openssl_certificate_module.html#openssl-certificate-module) dans le playbook de provisionning, option “ownca", on lui fait manger le CA : il crache un certif avec comme domaines ceux de la vm `*.prout.vm` ET `prout.vm`
> 3. on rajoute l’offloading par défaut dans nginx
> 4. Une bafouille dans le README :) 
> 5. Ajouter le CA à osX

**Comment by gfaivre** [comment]
On est d'accord que «mettre le certificat dans le navigateur» c'est installer le certificat dans le Keychain ? Ça vous évitera de devoir le faire pour chaque navigateur que vous utilisez.

**Comment by nervo** [comment]
@gfaivre installer le CA certificate dans les navigateurs. On va générer les certifs de chaque projet à partir de lui, du coup, on le fait pour un projet, on l'a fait pour tous les projets

**Comment by nervo** [comment]
Btw, it's on its way :) https://github.com/manala/manala-recipes/pull/79
